# Generated by Django 3.0.8 on 2020-07-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('types', models.CharField(choices=[('Drama', 'Drama'), ('Suspense', 'Suspence'), ('Thriller', 'Thriller'), ('Love', 'Love'), ('Si-Fi', 'Si-Fi'), ('Action', 'Action'), ('Comedy', 'Comedy')], default='Action', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('character_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstPage.Movie')),
                ('movies', models.ManyToManyField(related_name='Character', to='firstPage.Movie')),
            ],
        ),
    ]
