# Generated by Django 3.0.8 on 2020-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0002_jobapplicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='date_created',
        ),
        migrations.AddField(
            model_name='languages',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
