# Generated by Django 3.0.8 on 2020-08-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0003_auto_20200811_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
